name: ai_translator
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: "^3.0.0"

dependencies:
  build: ^2.3.0
  build_config: ^1.0.0
  dart_style: ^2.3.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
