name: hotel_booking_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

scripts: 
  gen: dart run build_runner watch 
  run:  flutter run -t lib/main.dart
  run-prod: fvm flutter run -t lib/main.dart 
  ipa: fvm flutter build ipa -t lib/main.dart --release
  ipa-prod: fvm flutter build ipa -t lib/main.dart --release

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  dio: ^5.7.0
  hydrated_bloc: ^9.1.5
  hive: ^2.2.3
  path_provider: ^2.1.1
  intl: ^0.19.0
  flutter_vibrate: ^1.3.0
  gap: ^3.0.1
  fluttertoast: ^8.2.10
  hive_flutter: ^1.1.0
  auto_route: ^7.8.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.1

  
dev_dependencies:
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  dependency_validator: any
  chopper_generator: ^8.0.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - secrets.json


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/WorkSans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans/WorkSans-Thin.ttf
          weight: 100

