name: core
description: pure Dart core features.
# version: 1.0.0
# homepage:

environment:
  sdk: ">=3.4.3 <4.0.0"

scripts:
  gen: dart run build_runner watch --delete-conflicting-outputs

dependencies:
 

  dio: ^5.5.0+1
  freezed_annotation: ^2.4.1
  logging: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  build_runner: ^2.4.6
  pedantic: ^1.11.0
  dependency_validator: any
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  chopper_generator: ^7.0.4
  hive_generator: ^2.0.1
 
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  test: ^1.25.7
